const Menus = [
  {
    path: '/admin/home/',
    title: '主页',
    icon: 'md-home',
    header: 'home',
    is_header: 1,
  },
  {
    path: '/admin/product',
    title: '商品',
    icon: 'md-basket',
    header: '0',
    is_header: 1,
    children: [
      {
        path: '/admin/product/product_list',
        title: '商品管理',
        icon: '',
        header: '',
        is_header: 0,
      },
      {
        path: '/admin/product/product_classify',
        title: '商品分类',
        icon: '',
        header: 'product',
        is_header: 0,
      },
      {
        path: '/admin/product/product_attr',
        title: '商品规格',
        icon: '',
        header: 'product',
        is_header: 1,
      },
      {
        path: '/admin/product/product_reply',
        title: '商品评论',
        icon: '',
        header: 'product',
        is_header: 0,
      },
    ],
  },
  {
    path: '/admin/order',
    title: '订单',
    icon: 'md-cart',
    header: 'home',
    is_header: 1,
    children: [
      {
        path: '/admin/order/list',
        title: '订单管理',
        icon: '',
        header: 'order',
        is_header: 0,
      },
      {
        path: '/admin/order/offline',
        title: '收银订单',
        icon: '',
        header: '',
        is_header: 0,
      },
      {
        path: '/admin/order/refund',
        title: '售后订单',
        icon: '',
        header: '',
        is_header: 0,
      },
    ],
  },
  {
    path: '/admin/user',
    title: '用户',
    icon: 'md-person',
    header: 'user',
    is_header: 1,
    children: [
      {
        path: '/admin/user/list',
        title: '用户管理',
        icon: '',
        header: 'user',
        is_header: 1,
      },
      {
        path: '/admin/user/group',
        title: '用户分组',
        icon: '',
        header: 'user',
        is_header: 1,
      },
      {
        path: '/admin/user/label',
        title: '用户标签',
        icon: '',
        header: 'user',
        is_header: 1,
      },
      {
        path: '/admin/user/level',
        title: '用户等级',
        icon: '',
        header: 'user',
        is_header: 1,
      },
    ],
  },
  {
    path: '/admin/agent',
    title: '分销',
    icon: 'ios-people',
    header: 'user',
    is_header: 1,
    children: [
      {
        path: '/admin/setting/system_config_retail/2/9',
        title: '分销设置',
        icon: '',
        header: 'setting',
        is_header: 0,
      },
      {
        path: '/admin/agent/agent_manage/index',
        title: '分销员管理',
        icon: '',
        header: 'user',
        is_header: 0,
      },
      {
        path: '/admin/setting/membership_level/index',
        title: '分销等级',
        icon: '',
        header: '',
        is_header: 0,
      },
    ],
  },
  {
    path: '/admin/kefu',
    title: '客服',
    icon: 'md-chatboxes',
    header: '',
    is_header: 0,
    children: [
      {
        path: '/admin/setting/store_service/index',
        title: '客服列表',
        icon: '',
        header: '',
        is_header: 0,
      },
      {
        path: '/admin/setting/store_service/speechcraft',
        title: '客服话术',
        icon: '',
        header: '',
        is_header: 0,
      },
      {
        path: '/admin/setting/store_service/feedback',
        title: '用户留言',
        icon: '',
        header: '',
        is_header: 0,
      },
    ],
  },
  {
    path: '/admin/marketing',
    title: '营销',
    icon: 'ios-paper-plane',
    header: 'home',
    is_header: 1,
    children: [
      {
        path: '/admin/marketing/store_coupon',
        title: '优惠券',
        icon: '',
        header: 'marketing',
        is_header: 1,
        children: [
          {
            path: '/admin/marketing/store_coupon_issue/index',
            title: '优惠券列表',
            icon: '',
            header: 'marketing',
            is_header: 1,
          },
          {
            path: '/admin/marketing/store_coupon_user/index',
            title: '用户领取记录',
            icon: '',
            header: 'marketing',
            is_header: 1,
          },
        ],
      },
      {
        path: '/admin/marketing/store_bargain',
        title: '砍价管理',
        icon: '',
        header: 'marketing',
        is_header: 0,
        children: [
          {
            path: '/admin/marketing/store_bargain/index',
            title: '砍价商品',
            icon: '',
            header: 'marketing',
            is_header: 1,
          },
          {
            path: '/admin/marketing/store_bargain/create',
            title: '添加砍价',
            icon: '',
            header: '',
            is_header: 0,
            auth: ['hidden'],
          },
          {
            path: '/admin/marketing/store_bargain/bargain_list',
            title: '砍价列表',
            icon: '',
            header: '',
            is_header: 0,
          },
        ],
      },
      {
        path: '/admin/marketing/store_combination',
        title: '拼团管理',
        icon: '',
        header: 'marketing',
        is_header: 0,
        children: [
          {
            path: '/admin/marketing/store_combination/index',
            title: '拼团商品',
            icon: '',
            header: 'marketing',
            is_header: 1,
          },
          {
            path: '/admin/marketing/store_combination/combina_list',
            title: '拼团列表',
            icon: '',
            header: 'marketing',
            is_header: 0,
          },
          {
            path: '/admin/marketing/store_combination/create',
            title: '添加拼团',
            icon: '',
            header: '',
            is_header: 0,
            auth: ['hidden'],
          },
        ],
      },
      {
        path: '/admin/marketing/store_seckill',
        title: '秒杀管理',
        icon: '',
        header: 'marketing',
        is_header: 0,
        children: [
          {
            path: '/admin/marketing/store_seckill/index',
            title: '秒杀商品',
            icon: '',
            header: 'marketing',
            is_header: 1,
          },
          {
            path: '/admin/marketing/store_seckill_data/index/49',
            title: '秒杀配置',
            icon: '',
            header: 'marketing',
            is_header: 1,
          },
          {
            path: '/admin/marketing/store_seckill/create',
            title: '添加秒杀',
            icon: '',
            header: '',
            is_header: 0,
            auth: ['hidden'],
          },
        ],
      },
      {
        path: '/admin/marketing/user_point',
        title: '积分管理',
        icon: '',
        header: 'marketing',
        is_header: 1,
        children: [
          {
            path: '/admin/marketing/integral/system_config/3/11',
            title: '积分配置',
            icon: '',
            header: 'marketing',
            is_header: 1,
          },
          {
            path: '/admin/marketing/user_point/index',
            title: '积分日志',
            icon: '',
            header: 'marketing',
            is_header: 0,
          },
          {
            path: '/admin/setting/system_group_data/sign/55',
            title: '签到配置',
            icon: '',
            header: '',
            is_header: 0,
          },
          {
            path: '/admin/marketing/store_integral/index',
            title: '积分商品',
            icon: '',
            header: '',
            is_header: 0,
          },
          {
            path: '/admin/marketing/store_integral/create',
            title: '添加积分商品',
            icon: '',
            header: '',
            is_header: 0,
            auth: ['hidden'],
          },
          {
            path: '/admin/marketing/store_integral/order_list',
            title: '积分订单',
            icon: '',
            header: '',
            is_header: 0,
          },
          {
            path: '/pages/marketing/store_integral/add_store_integral',
            title: '批量添加积分商品',
            icon: '',
            header: '',
            is_header: 0,
            auth: ['hidden'],
          },
        ],
      },
      {
        path: '/admin/marketing/live',
        title: '直播管理',
        icon: '',
        header: '',
        is_header: 0,
        children: [
          {
            path: '/admin/marketing/live/live_room',
            title: '直播间管理',
            icon: '',
            header: '',
            is_header: 0,
          },
          {
            path: '/admin/marketing/live/live_goods',
            title: '直播商品管理',
            icon: '',
            header: '',
            is_header: 0,
          },
          {
            path: '/admin/marketing/live/anchor',
            title: '主播管理',
            icon: '',
            header: '',
            is_header: 0,
          },
        ],
      },
      {
        path: '/admin/marketing/presell',
        title: '预售管理',
        icon: '',
        header: '',
        is_header: 0,
        children: [
          {
            path: '/admin/marketing/presell/index',
            title: '预售商品',
            icon: '',
            header: '',
            is_header: 0,
          },
          {
            path: '/admin/marketing/presell/create',
            title: '添加预售',
            icon: '',
            header: '',
            is_header: 0,
            auth: ['hidden'],
          },
        ],
      },
      {
        path: '/admin/marketing/lottery/index',
        title: '九宫格抽奖',
        icon: '',
        header: '',
        is_header: 0,
      },
    ],
  },
  {
    path: '/admin/finance',
    title: '财务',
    icon: 'logo-usd',
    header: 'home',
    is_header: 0,
    children: [
      {
        path: '/admin/finance/user_extract',
        title: '财务操作',
        icon: '',
        header: 'finance',
        is_header: 0,
        children: [
          {
            path: '/admin/finance/user_extract/index',
            title: '提现申请',
            icon: '',
            header: 'finance',
            is_header: 0,
          },
          {
            path: '/admin/order/invoice/list',
            title: '发票管理',
            icon: '',
            header: '',
            is_header: 0,
          },
        ],
      },
      {
        path: '/admin/finance/user_recharge',
        title: '财务记录',
        icon: '',
        header: 'finance',
        is_header: 0,
        children: [
          {
            path: '/admin/finance/user_recharge/index',
            title: '充值记录',
            icon: '',
            header: 'finance',
            is_header: 0,
          },
          {
            path: '/admin/finance/finance/bill',
            title: '资金记录',
            icon: '',
            header: 'finance',
            is_header: 0,
          },
        ],
      },
      {
        path: '/admin/finance/finance',
        title: '佣金记录',
        icon: '',
        header: 'finance',
        is_header: 0,
        children: [
          {
            path: '/admin/finance/finance/commission',
            title: '佣金记录',
            icon: '',
            header: 'finance',
            is_header: 0,
          },
        ],
      },
    ],
  },
  {
    path: '/admin/cms',
    title: '内容',
    icon: 'ios-book',
    header: 'home',
    is_header: 0,
    children: [
      {
        path: '/admin/cms/article/index',
        title: '文章管理',
        icon: '',
        header: 'cms',
        is_header: 0,
      },
      {
        path: '/admin/cms/article_category/index',
        title: '文章分类',
        icon: '',
        header: 'cms',
        is_header: 0,
      },
    ],
  },
  {
    path: '/admin/setting',
    title: '设置',
    icon: 'md-settings',
    header: 'setting',
    is_header: 1,
    children: [
      {
        path: '/admin/setting/system_config',
        title: '系统设置',
        icon: '',
        header: 'setting',
        is_header: 1,
      },
      {
        path: '/admin/setting/sms/sms_config/index',
        title: '一号通',
        icon: '',
        header: 'setting',
        is_header: 1,
      },
      {
        path: '/admin/setting/pages',
        title: '页面管理',
        icon: '',
        header: '',
        is_header: 0,
        children: [
          {
            path: '/admin/setting/pages/devise',
            title: '页面设计',
            icon: '',
            header: '',
            is_header: 0,
          },
          {
            path: '/admin/setting/pages/diy',
            title: '页面编辑',
            icon: '',
            header: '',
            is_header: 0,
            auth: ['hidden'],
          },
          {
            path: '/admin/setting/system_visualization_data',
            title: '数据配置',
            icon: '',
            header: 'system',
            is_header: 1,
          },
          {
            path: '/admin/setting/theme_style',
            title: '主题风格',
            icon: '',
            header: '',
            is_header: 0,
          },
          {
            path: '/admin/setting/pc_group_data',
            title: 'PC商城',
            icon: '',
            header: '',
            is_header: 0,
          },
        ],
      },
      {
        path: '/admin/setting/auth/list',
        title: '管理权限',
        icon: '',
        header: 'setting',
        is_header: 1,
        children: [
          {
            path: '/admin/setting/system_role/index',
            title: '角色管理',
            icon: '',
            header: 'setting',
            is_header: 1,
          },
          {
            path: '/admin/setting/system_admin/index',
            title: '管理员列表',
            icon: '',
            header: 'setting',
            is_header: 0,
          },
          {
            path: '/admin/setting/system_menus/index',
            title: '权限规则',
            icon: '',
            header: 'setting',
            is_header: 0,
          },
        ],
      },
      {
        path: '/admin/setting/freight',
        title: '发货设置',
        icon: '',
        header: '',
        is_header: 0,
        children: [
          {
            path: '/admin/setting/delivery_service/index',
            title: '配送员管理',
            icon: '',
            header: '',
            is_header: 0,
          },
          {
            path: '/admin/setting/merchant/system_store/index',
            title: '提货点设置',
            icon: '',
            header: '',
            is_header: 0,
            children: [
              {
                path: '/admin/setting/merchant/system_store/list',
                title: '提货点',
                icon: '',
                header: 'setting',
                is_header: 1,
              },
              {
                path: '/admin/setting/merchant/system_store_staff/index',
                title: '核销员',
                icon: '',
                header: 'setting',
                is_header: 1,
              },
              {
                path: '/admin/setting/merchant/system_verify_order/index',
                title: '核销订单',
                icon: '',
                header: 'setting',
                is_header: 1,
              },
            ],
          },
          {
            path: '/admin/setting/freight/shipping_templates/list',
            title: '运费模板',
            icon: '',
            header: 'setting',
            is_header: 1,
          },
        ],
      },
      {
        path: '/admin/setting/notification/index',
        title: '消息管理',
        icon: '',
        header: '',
        is_header: 0,
      },
    ],
  },
  {
    path: '/admin/app',
    title: '应用',
    icon: 'md-cube',
    header: 'app',
    is_header: 1,
    children: [
      {
        path: '/admin/app/wechat',
        title: '公众号',
        icon: '',
        header: 'app',
        is_header: 1,
        children: [
          {
            path: '/admin/app/wechat/setting/menus/index',
            title: '微信菜单',
            icon: '',
            header: 'app',
            is_header: 0,
          },
          {
            path: '/admin/app/wechat/news_category/index',
            title: '图文管理',
            icon: '',
            header: 'app',
            is_header: 0,
          },
          {
            path: '/admin/app/wechat/news_category/save',
            title: '图文添加',
            icon: '',
            header: 'app',
            is_header: 1,
            auth: ['hidden'],
          },
          {
            path: '/admin/app/wechat/reply',
            title: '自动回复',
            icon: '',
            header: 'app',
            is_header: 0,
            children: [
              {
                path: '/admin/app/wechat/reply/follow/subscribe',
                title: '微信关注回复',
                icon: '',
                header: 'app',
                is_header: 0,
              },
              {
                path: '/admin/app/wechat/reply/keyword',
                title: '关键字回复',
                icon: '',
                header: 'app',
                is_header: 0,
              },
              {
                path: '/admin/app/wechat/reply/index/default',
                title: '无效关键词回复',
                icon: '',
                header: 'app',
                is_header: 0,
              },
              {
                path: '/admin/app/wechat/reply/keyword/save',
                title: '关键字添加',
                icon: '',
                header: 'app',
                is_header: 1,
                auth: ['hidden'],
              },
            ],
          },
        ],
      },
      {
        path: '/admin/app/routine',
        title: '小程序',
        icon: '',
        header: '',
        is_header: 0,
        children: [
          {
            path: '/admin/app/routine/download',
            title: '小程序下载',
            icon: '',
            header: '',
            is_header: 0,
          },
        ],
      },
    ],
  },
  {
    path: '/admin/system',
    title: '维护',
    icon: 'md-hammer',
    header: 'setting',
    is_header: 1,
    children: [
      {
        path: '/admin/system/config',
        title: '开发配置',
        icon: '',
        header: 'system',
        is_header: 1,
        children: [
          {
            path: '/admin/system/config/system_config_tab/index',
            title: '配置分类',
            icon: '',
            header: 'system',
            is_header: 0,
          },
          {
            path: '/admin/system/config/system_group/index',
            title: '组合数据',
            icon: '',
            header: 'system',
            is_header: 0,
          },
          {
            path: '/admin/system/config/system_config_tab/list',
            title: '配置列表',
            icon: '',
            header: 'system',
            is_header: 1,
            auth: ['hidden'],
          },
          {
            path: '/admin/system/config/system_group/list',
            title: '组合数据列表',
            icon: '',
            header: 'system',
            is_header: 1,
            auth: ['hidden'],
          },
        ],
      },
      {
        path: '/admin/system/maintain',
        title: '安全维护',
        icon: '',
        header: 'system',
        is_header: 1,
        children: [
          {
            path: '/admin/system/maintain/clear/index',
            title: '刷新缓存',
            icon: '',
            header: 'system',
            is_header: 1,
          },
          {
            path: '/admin/system/maintain/system_log/index',
            title: '系统日志',
            icon: '',
            header: 'system',
            is_header: 0,
          },
          {
            path: '/admin/system/maintain/system_file/index',
            title: '文件校验',
            icon: '',
            header: 'system',
            is_header: 0,
          },
          {
            path: '/admin/system/maintain/system_cleardata/index',
            title: '清除数据',
            icon: '',
            header: 'system',
            is_header: 0,
          },
          {
            path: '/admin/system/maintain/system_databackup/index',
            title: '数据备份',
            icon: '',
            header: 'system',
            is_header: 0,
          },
          {
            path: '/admin/system/log',
            title: '日志',
            icon: '',
            header: '',
            is_header: 0,
            auth: ['hidden'],
          },
        ],
      },
      {
        path: '/admin/setting/freight/express/index',
        title: '物流公司',
        icon: '',
        header: '',
        is_header: 0,
      },
      {
        path: '/admin/setting/freight/city/list',
        title: '城市数据',
        icon: '',
        header: 'setting',
        is_header: 1,
      },
      {
        path: '/admin/system/file',
        title: '附件管理',
        icon: '',
        header: '',
        is_header: 0,
      },
      {
        path: '/admin/system/maintain/auth',
        title: '商业授权',
        icon: '',
        header: '',
        is_header: 0,
      },
    ],
  },
];
export default Menus;
